version: '3.7'

services:
  hook:
    image: oven/bun
    volumes:
      - ./:/home/bun/app
    ports:
      - '${SERVER_PORT:-3000}:${SERVER_PORT:-3000}'
    command: bun start
    init: true
    restart: always