services:
  discord-bot:
    image: '${APP_IMAGE:-animethemes-discord:local}'
    container_name: discord-bot
    working_dir: /app
    restart: on-failure:10
    env_file: .env
    ports:
      - "127.0.0.1:${API_PORT:-3000}:${API_PORT:-3000}"
    networks:
      - shared-network
networks:
  shared-network:
    external: true