services:
  discord-bot:
    build:
      context: .
    container_name: discord-bot
    working_dir: /app
    restart: on-failure:10
    env_file: .env
    ports:
      - "127.0.0.1:${API_PORT:-3000}:${API_PORT:-3000}"
    extra_hosts:
      - "graphql.animethemes.moe:host-gateway"
